
drop table UserPermissions
drop table Users
drop table bbTenants
drop table bbList
drop table bbListTypes
drop table bb_Asset_Category
drop table bb_Asset_Make
drop table bb_Asset_Model
drop table bb_Asset_Vendor
drop table bbRequestGroups
drop table bbRequestItems
drop table bbItemPurchases
drop table bbItems 
drop table bbItemsTypes
drop table bbOrders
drop table bbOrderGroups
drop table bbInventoryItems 
drop table bbOrderItems
drop table bbOrderPayments
drop table bbItemTypes 
drop table bbListCurrencies 
drop table Groups
drop table FW_Inventory
drop table __MigrationHistory
